version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: healthindex
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/healthindex
      DATAUSA_API_URL: https://datausa.io/api/data

volumes:
  postgres_data:
